# hw2
## 8.
library(graphics)
library(MASS)
# install.packages("ISLR")
library(ISLR) 
data(Auto) 
summary(Auto) 
# head(Auto) 
# View(Auto)

# mydata <- read.csv(file = "/Users/wei/Desktop/Auto.csv")
# head(mydata)
# mydata$origin = as.numeric(mydata$origin)
# mydata$horsepower = as.numeric(mydata$horsepower)
lm.fit = lm(mpg~horsepower, data=Auto)
summary(fit)
# 8.(a) iv.
predict(lm.fit, newdata = data.frame(horsepower=c(98)), interval="confidence")
predict(lm.fit, newdata = data.frame(horsepower=c(98)), interval="prediction")
# 8.(b) 
plot(Auto$horsepower, Auto$mpg, main="Scatterplot",ylab="mpg",xlab="horsepower")
abline(lm.fit, lwd=3, col="red")
# 8.(c)
par(mfrow=c(2,2))
plot(lm.fit)
## 9.(a)
plot(Auto)
# 9.(b)
cor(Auto[, !(names(Auto)=="name")])
# 9.(c)
lm.fit = lm(mpg~.-name, data=Auto)
summary(lm.fit)
# 9.(d)
par(mfrow=c(2,2))
plot(lm.fit)
# 9.(e)
lm.fit.inter = lm(mpg ~ (.-name)*(.-name), data=Auto)
summary(lm.fit.inter)
# 9.(f)
Auto_2 <- Auto
head(Auto_2)
# 平方
Auto_2[2:8] <- lapply(Auto_2[2:8], function(x) x^2)
colnames(Auto_2) <- c("mpg", "cylinders^2", "displacement^2", "horsepower^2", "weight^2", "acceleration^2", "year^2", "origin^2","name")
head(Auto_2)
lm.fit = lm(mpg ~ (.-name), data=Auto_2)
summary(lm.fit)

Auto_3 <- Auto
# 取log
Auto_3[2:8] <- lapply(Auto_3[2:8], function(x) log(x))
colnames(Auto_3) <- c("mpg", "log(cylinders)", "log(displacement)", "log(horsepower)", "log(weight)", "log(acceleration)", "log(year)", "log(origin)","name")
head(Auto_3)
lm.fit = lm(mpg ~ (.-name), data=Auto_3)
summary(lm.fit)

Auto_4 <- Auto
# 開根號
Auto_4[2:8] <- lapply(Auto_4[2:8], function(x) sqrt(x))
colnames(Auto_4) <- c("mpg", "sqrt(cylinders)", "sqrt(displacement)", "sqrt(horsepower)", "sqrt(weight)", "sqrt(acceleration)", "sqrt(year)", "sqrt(origin)","name")
head(Auto_4)
lm.fit = lm(mpg ~ (.-name), data=Auto_4)
summary(lm.fit)

# 10.(a)
# install.packages("ISLR")
library(ISLR)
summary(Carseats)
head(Carseats)
lm.fit = lm(Sales~Price+Urban+US,data=Carseats)
summary(lm.fit)
# 10.(e)
lm.fit = lm(Sales~Price+US,data=Carseats)
summary(lm.fit)
# 10.(g)
confint(lm.fit)
# 10.(h)
plot(lm.fit)
